### ISSUE TITLE
`llvm-hs-pretty` produces invalid IR where `llvm-hs` produces valid IR

### ISSUE THREAD

**Issue by aherrmann** [llvm-hs/llvm-hs-pretty#15]
I noticed two cases where `llvm-hs` accepts and seemingly implicitly corrects an `LLVM.AST.Module` that is in principle ill-formed.
`llvm-hs-pretty` on the other hand produces IR that will then be rejected by the LLVM parser.

The following code demonstrates those two cases:

``` haskell
{-# LANGUAGE OverloadedStrings #-}

import Control.Exception
import Data.ByteString (ByteString)
import qualified Data.ByteString.Lazy
import qualified Data.Text.Lazy.Encoding

import LLVM.AST as AST
import LLVM.AST.Constant
import LLVM.AST.Global
import LLVM.AST.Type

import LLVM.Context
import LLVM.Exception
import LLVM.Module

import LLVM.Pretty

example1 :: AST.Module
example1 = defaultModule
  { moduleDefinitions =
      [ GlobalDefinition functionDefaults
          { name = "test"
          , returnType = void
          , basicBlocks =
              [ BasicBlock "entry"
                  [ UnName 0 := Alloca i32 Nothing 0 []
                  , UnName 1 := Store False (LocalReference (ptr i32) (UnName 0)) (ConstantOperand (Int 32 42)) Nothing 0 []
                  ]
                  (Do $ Ret Nothing [])
              ]
          }
      ]
  }

example2 :: AST.Module
example2 = defaultModule
  { moduleDefinitions =
      [ GlobalDefinition functionDefaults
          { name = "test"
          , returnType = void
          , basicBlocks =
              [ BasicBlock "entry"
                  [ UnName 0 := Alloca (ptr $ FunctionType void [] False) Nothing 0 []
                  , Do $ Store False
                      (LocalReference (ptr $ ptr $ FunctionType void [] False) (UnName 0))
                      (ConstantOperand $ GlobalReference (FunctionType void [] False) "test")
                      Nothing 0 []
                  ]
                  (Do $ Ret Nothing [])
              ]
          }
      ]
  }


prettyLLVMAssembly :: AST.Module -> ByteString
prettyLLVMAssembly = Data.ByteString.Lazy.toStrict . Data.Text.Lazy.Encoding.encodeUtf8 . ppllvm


llvmAssembly :: AST.Module -> IO ByteString
llvmAssembly ast =
  withContext $ \ctx ->
  withModuleFromAST ctx ast moduleLLVMAssembly


parseLLVMAssembly :: ByteString -> IO (Either ParseFailureException ())
parseLLVMAssembly s = try $
  withContext $ \ctx ->
  withModuleFromLLVMAssembly ctx s $ \_ ->
  pure ()


main :: IO ()
main = do
  putStrLn "Example 1: Instructions returning void are implicitly un-named" 
  putStrLn $ replicate 50 '='
  putStrLn "Using llvm-hs:"
  printResult =<< parseLLVMAssembly =<< llvmAssembly example1
  putStrLn $ replicate 50 '-'
  putStrLn "Using llvm-hs-pretty:"
  printResult =<< parseLLVMAssembly (prettyLLVMAssembly example1)

  putStrLn ""
  
  putStrLn "Example 2: Global references to functions are implicitly cast to pointers" 
  putStrLn $ replicate 50 '='
  putStrLn "Using llvm-hs:"
  printResult =<< parseLLVMAssembly =<< llvmAssembly example2
  putStrLn $ replicate 50 '-'
  putStrLn "Using llvm-hs-pretty:"
  printResult =<< parseLLVMAssembly (prettyLLVMAssembly example2)

  where
    printResult (Right ()) = putStrLn "OK" 
    printResult (Left (ParseFailureException err)) = putStr err
```

In the first example an instruction that produces `void` is named, which is illegal.
In the second example a global reference to a function is not typed as function pointer, which it should be.

The above code produces the following output:

```
Example 1: Instructions returning void are implicitly un-named
==================================================
Using llvm-hs:
OK
--------------------------------------------------
Using llvm-hs-pretty:
<string>:6:3: error: instructions returning void cannot have a name
  %1 = store i32 42, i32* %0
  ^

Example 2: Global references to functions are implicitly cast to pointers
==================================================
Using llvm-hs:
OK
--------------------------------------------------
Using llvm-hs-pretty:
<string>:6:17: error: functions are not values, refer to them as pointers
  store void () @test, void ()** %0
                ^
```

I'm actually not sure at what stage those implicit corrections happen.
It might well be that this happens within llvm itself (i.e. outside of llvm-hs).
I'm also not sure if `llvm-hs-pretty` should even try to emulate those implicit corrections.
However, in any case its a pitfall to be aware of.

**Comment by cocreature** [comment]
Thanks for the detailed bug report! I’ll take a closer look at the examples during the next days.

**Comment by cocreature** [comment]
Alright, I looked into this. So we have two different problems here:
1. LLVM’s internal representation actually doesn’t care about the names and numbers you give to instructions since references are just represented as a pointer. In `llvm-hs` they are used to figure out to create this pointers appropriately but if you use `UnName` the name is never passed to LLVM itself. If you use `Name` you will get an error from LLVM for this example. I haven’t yet looked into how difficult it would be to check this in `llvm-hs` itself but it seems doable (first create the LLVM instruction, get its type and complain if it’s void and there is a name). I’ll look into this at some point if nobody gets to it before me.
2. The implicit cast is quite simple to explain: When serializing `GlobalReference` to LLVM’s internal representation we just completely ignore the type since LLVM infers it from the thing you’re referring to. Again I haven’t looked too deeply into how easy adding a check here would be but it seems quite doable.

**Comment by cocreature** [comment]
I’ve added the additional checks in `llvm-hs` so I’m closing this issue.

**Comment by aherrmann** [comment]
@cocreature  Thanks a lot for looking into this and adding the checks!
