### ISSUE TITLE
Instruction Metadata

### ISSUE THREAD

**Issue by sdiehl** [llvm-hs/llvm-hs-pretty#30]
Currently most of the pretty printers toss out the optional instruction-level metadata. This should be as simple as writing a pretty printer for the [`InstructionMetadata`](https://hackage.haskell.org/package/llvm-hs-pure-5.1.0/docs/LLVM-AST-Instruction.html#t:InstructionMetadata) instance and propagating it to the instruction printers.

**Comment by sdiehl** [comment]
Was thinking about just pushing this story off until the next release. I think `llvm-hs-pretty` is pretty much feature complete to upload to a 0.1 version on Hackage.

**Comment by cocreature** [comment]
Sounds good!
