### ISSUE TITLE
Migrate Typed.hs to llvm-hs

### ISSUE THREAD

**Issue by sdiehl** [llvm-hs/llvm-hs-pretty#32]
The only reason we pull this library in as a dependency in `irbuilder` is to not reimplement the typing logic implemented in `Typed.hs`. Which makes me think we should just migrate it up into `llvm-hs-pure` since it's not really related to the pretty printer at all.

https://github.com/llvm-hs/llvm-hs-pretty/blob/master/src/LLVM/Typed.hs

**Comment by cocreature** [comment]
Yeah I noticed that as well, I’m all for moving it to `llvm-hs-pure`!

**Comment by sdiehl** [comment]
Cool, I'll extract it and PR it.
