### ISSUE TITLE
llvm-dev-5.0 needed?

### ISSUE THREAD

**Issue by nomeata** [llvm-hs/llvm-hs-pretty#35]
The `README.md` says

> ## Usage
>
>     sudo apt-get install llvm-dev-5.0
>
> There is a single function ppllvm that maps a LLVM.AST.Module to a String.

without explaining why the C package needs to be installed. This is confusing, since it also says

> Goal is to be able to pretty print a sufficiently large subset of the LLVM AST from pure Haskell without having to go through the C++ API.

Is it only needed for the tests maybe?

**Comment by cocreature** [comment]
Good catch! I’ve added a note to the readme that this is only required for the test suite.

**Comment by sdiehl** [comment]
Yeah it's not needed. It's just used for the round-tripping tests to make sure the Haskell and C++ match.
