### ISSUE TITLE
Inconsistent with llvm-hs when using 'Null' 

### ISSUE THREAD

**Issue by DKXXXL** [llvm-hs/llvm-hs-pretty#38]
(First time submitting issues, sorry for any inconvenience in advance)

When using (ppllvm) llvm-hs-pretty-0.1.0.0 and expressing 'Null' from LLVM.AST.Constant, the output would be different from the one 

when I use (moduleLLVMAssembly) llvm-hs (I don't remember the version, but in cabal file, I denote "llvm-hs >= 4.0.0.0", so I believe it's the latest version in hackage) with the same LLVM.AST.Module.

More specifically,
`Null (IntegerType 8)`
 would be translated into a pointer in llvm-hs but a "i8 zeroinitializer" in llvm-hs-pretty.

I am not sure which one is the real meaning for 'Null' constructor, but I think llvm-hs is doing correctly.

**Comment by sdiehl** [comment]
Can you put together a gist that contains the minimal example where `llvm-hs` and `llvm-hs-pretty` differ in their outputs. The LLVM AST doesn't actually enforce correct composition in it's datatypes so it is entirely possible to construct nonsensical IR which llvm-hs-pretty will try to print but obviously wouldn't pass the `verify` pass.

**Comment by sdiehl** [comment]
Where is `ptype` brought into scope?

**Comment by DKXXXL** [comment]
I am sorry. The current version https://gist.github.com/DKXXXL/0bd9f69d7a134d88921e7758f26f1d5a
should be runnable.
The packages are
llvm-hs-5.1.3
llvm-hs-pure-5.1.2
llvm-hs-pretty-0.1.0.0

The cabal file
  build-depends:
      base                 >= 4.7 && <5
    , haskeline            >= 0.7.1.2
    , llvm-hs              >= 4.0.0.0
    , llvm-hs-pure         >= 4.0.0.0
    , llvm-hs-pretty >= 0.1.0.0
    , parsec               >= 3.1
    , mtl                  >= 2.1.3
    , transformers         >= 0.3.0.0 && < 0.6
    , containers           >= 0.4
    , text >= 1.2.2.1
    , bytestring  >= 0.10.8.0

A large amount of code is from kaleidoscope.

**Comment by sdiehl** [comment]
Thanks, I can work with this.

**Comment by cocreature** [comment]
Afaict the problem here is that `null` has to be of pointer type, see https://llvm.org/docs/LangRef.html#simple-constants so the only thing that we can do is try to reject this in `llvm-hs` (which we should do).

**Comment by sdiehl** [comment]
Indeed, since this is malformed AST the best we can do is just have the pretty printer just panic if given a non-pointer type.

**Comment by sdiehl** [comment]
For what it's worth, this would be rejected by the [`llvm-hs-typed`](https://github.com/llvm-hs/llvm-hs-typed/blob/master/src/LLVM/AST/Tagged/Constant.hs#L91) AST. :wink:

**Comment by sdiehl** [comment]
@DKXXXL If this is "solved", I'll close out the issue. The overarching story is that `llvm-hs` doesn't actually enforce the correctness of the IR at the datatype level (yet) so we're limited to workarounds.
