### ISSUE TITLE
Support for Inline Assembly

### ISSUE THREAD

**Issue by jmittert** [llvm-hs/llvm-hs-pretty#50]
I suppose this is a feature/extension request.

Trying to pretty print a Call AST node where the function is `Left (IA.InlineAssembly {...})` currently isn't implemented and gives `"Non-callable argument. (Malformed AST)"` despite llvm-hs having support for it.

I've got it "working" in [my fork](https://github.com/jmittert/llvm-hs-pretty/commit/2c32b3daa71e19aa42b1a592964c9468074b91d2). I can PR it if it's helpful, though to be honest, I didn't really know what I was doing.

**Comment by sdiehl** [comment]
Yes, a pull request would be very welcome.

**Comment by sdiehl** [comment]
This is pushed in the latest release: https://hackage.haskell.org/package/llvm-hs-pretty-0.4.0.0
