### ISSUE TITLE
load and store instructions don't handle atomicity

### ISSUE THREAD

**Issue by SongWithoutWords** [llvm-hs/llvm-hs-pretty#59]
https://github.com/llvm-hs/llvm-hs-pretty/blob/5fea706dda0eff4f819fa762de1735675496872a/src/LLVM/Pretty.hs#L506-L508

**Comment by sdiehl** [comment]
Fixed in https://github.com/llvm-hs/llvm-hs-pretty/commit/49e2780d7d0b51c0d9ebc4c1dcfee25425a5b8c5 .
