### ISSUE TITLE
Add to stackage?

### ISSUE THREAD

**Issue by jaseemabid** [llvm-hs/llvm-hs-pretty#7]

**Comment by sdiehl** [comment]
We will, once it stabilizes and has the entire IR specification. For now you can add it in your `stack.yaml` file and point it at Github.

**Comment by jdreaver** [comment]
Hey @sdiehl, it's been almost a year since this issue was opened. Is there anything else that needs to be done to add `llvm-hs-pretty` to Stackage? This library is a lifesaver and I'd love the added convenience of it being in Stackage.

Thanks again for this awesome library!

**Comment by sdiehl** [comment]
You should be able to download it today:

https://hackage.haskell.org/package/llvm-hs-pretty-0.1.0.0

**Comment by jdreaver** [comment]
Ah I was referring to Stackage, not Hackage (https://www.stackage.org/package/llvm-hs-pretty). Indeed currently I just add `llvm-hs-pretty-0.2.0.0` to `extra-deps` in my `stack.yaml`.

**Comment by sdiehl** [comment]
This is ready to go but is blocked upstream on this Stackage failure of `wl-pprint-text`.
https://github.com/ivan-m/wl-pprint-text/issues/18

**Comment by sdiehl** [comment]
https://www.stackage.org/nightly-2018-05-14/package/llvm-hs-pretty-0.3.0.0
