### ISSUE TITLE
Non-exhaustive patterns

### ISSUE THREAD

**Issue by fduxiao** [llvm-hs/llvm-hs-pretty#73]
src/LLVM/Pretty.hs:530:13-48: Non-exhaustive patterns in PointerType argTy _

I got this error when buiding some IR with llvm-hs-pretty

**Comment by cocreature** [comment]
Can you show us the IR? Is this a compile error or a runtime error?

**Comment by sdiehl** [comment]
There are cases where you can construct llvm-hs ASTs that are invalid IR and they can't be printed. Thus the non-exhaustive patterns. Make sure that your IR passes the verifier first and then post it here.

**Comment by fduxiao** [comment]
Here's my code. I'm following this [guide](http://www.stephendiehl.com/llvm) generating them. 

```haskell
module Main where

import Data.Text.Lazy (unpack)
import Data.String
import LLVM.AST
import LLVM.Pretty
import LLVM.AST.Global


printModule :: Module -> IO ()
printModule = putStr. unpack . ppllvm

double :: Type
double = FloatingPointType DoubleFP

makeName :: String -> Name
makeName = Name . fromString

local ::  Name -> Operand
local = LocalReference double

ret :: Operand -> Named Terminator
ret val = Do $ Ret (Just val) []

func :: Definition
func = GlobalDefinition $ functionDefaults {
    name          = makeName "foo"
    , parameters  = ([Parameter double (makeName "a") []], False)
    , returnType  = double
    , basicBlocks = [
        BasicBlock (makeName "entry") [
            UnName 1 := Alloca double Nothing 0 []
            , UnName 2 := Store False (local $ UnName 1) (local $ makeName "a") Nothing 0 []
            , UnName 3 := Load False (local $ UnName 1) Nothing 0 []
        ] (ret . local $ UnName 3)
    ]
}


main :: IO ()
main = printModule $ defaultModule {
    moduleName = fromString "some name"
    , moduleDefinitions = [func]
}
```

**Comment by sdiehl** [comment]
Your `load` instruction needs to be loading from a pointer type `double*` instead of `double`.

**Comment by fduxiao** [comment]
@sdiehl I finally found how the problem happened. I think it might be the problem with your tutorial of kaleidoscope. I opened another [issue](https://github.com/sdiehl/kaleidoscope/issues/51) under that repo illustrating it.

**Comment by sdiehl** [comment]
Made a note about non-exhaustive pattern and tried to add some more informative error messages. I'm in the process of fixing the kaleidoscope tutorial so it's up to date as well. That's about all I can do so closing out this issue.
