### ISSUE TITLE
Hackage maintainer

### ISSUE THREAD

**Issue by andrew-wja** [llvm-hs/llvm-hs-pretty#82]
@sdiehl Hi Stephen, could I ask you to add me (Hackage user account `andrew_wja`) to the maintainers of `llvm-hs-pretty` on Hackage? I know (from asking questions on llvm.discourse.group) that the LLVM devs tend to treat the textual IR as a second-class citizen after the bitcode representation, but I've found it incredibly useful in my own work with LLVM, so I'd like to make a matching llvm-hs-pretty-9.0.1.1 release on Hackage to accompany the upcoming llvm-hs-9.0.1.1 bugfix/improvement release.

**Comment by sdiehl** [comment]
Ok sure I'll add you to Hackage.

**Comment by sdiehl** [comment]
You're a maintainer on Hackage now. Cheers.
